### ISSUE TITLE
"Protocol not found" error

### ISSUE THREAD

**Issue by Mennaruuk** [itsachrafmansari/yt_downloader#1]
Hi! I'm encountering this error when I'm downloading this video. I still get a .webm file, but there is no sound in it.
```
[Menna@linux Downloads]$ python main.py
What yo want to download ? [v] for video and [p] for playlist : v
______________________________________________________________________
In what format you want to download it ? [v] for video and [a] for audio : v
______________________________________________________________________
Write the link : youtube.com/watch?v=gqMxf52CCmk
______________________________________________________________________
Loading, please wait...
______________________________________________________________________
Here's the available resolutions :

144p
240p
360p
480p
720p
1080p
1440p
2160p
Choose a reso [e.g. 1440]: 1080p
Video titled [❄️🇬🇧 London Snow Day 🇬🇧❄️] started downloading
ffmpeg version n4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-shared --enable-version3
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
C:\Users\Menna\Downloads/❄️🇬🇧 London Snow Day 🇬🇧❄️.mp4: Protocol not found
Did you mean file:C:\Users\Menna\Downloads/❄️🇬🇧 London Snow Day 🇬🇧❄️.mp4?
Traceback (most recent call last):
  File "/home/Menna/Downloads/main.py", line 156, in <module>
    dl_a_vid(video)
  File "/home/Menna/Downloads/main.py", line 91, in dl_a_vid
    ffmpeg.output(audio_stream, video_stream, final_file).run()
  File "/home/Menna/.local/lib/python3.9/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
```

**Comment by itsachrafmansari** [comment]
Hi @Mennaruuk,

I think you wrote your download folder path as following :
> C:\Users\Menna\Downloads/

make sure to remove any `/` or `\` from its end, so it becomes :
> C:\Users\Menna\Downloads

**Comment by Mennaruuk** [comment]
My bad: I'm using Linux now, not Windows, so the folder path should look more like:
```/home/Menna/Downloads```
I discovered that while an ending backslash is harmless, a forward slash will prompt an error, at least on Linux:
```
  File "/home/Menna/Downloads/main.py", line 10
    dlpath = '/home/Menna/Downloads\'  # Choose a download folder
                                                                    ^
SyntaxError: EOL while scanning string literal
```
I appreciate your help!
